/*
 * Copyright (c) 2020 Antmicro <www.antmicro.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __INC_BOARD_H
#define __INC_BOARD_H

#include <soc_pinmap.h>

#define UART_TX_PAD		44
#define UART_TX_PAD_CFG		UART_TXD_PAD44
#define UART_RX_PAD		45
#define UART_RX_PAD_CFG		UART_RXD_PAD45

#define UART_RX_SEL		UART_RXD_SEL_PAD45

#ifdef CONFIG_SPI_EOS_S3
#define SPI_CLK_PAD		34
#define SPI_MISO_PAD		36
#define SPI_MOSI_PAD		38
#define SPI_SS1_PAD		39

#define SPI_CLK_PAD_CFG		SPI_CLK_PAD34
#define SPI_MISO_PAD_CFG	SPI_MISO_PAD36
#define SPI_MOSI_PAD_CFG	SPI_MOSI_PAD38
#define SPI_SS1_PAD_CFG		SPI_SS1_PAD39
#endif /* CONFIG_SPI_EOS_S3 */

#ifdef CONFIG_PWM_GEN_EOS_S3
/* FPGA IP core peripherals */
#define DT_PWM_GEN_EOS_S3_BASE_ADDRESS		DT_QUICKLOGIC_EOS_S3_PWM_GEN_40020000_BASE_ADDRESS
#define DT_PWM_GEN_EOS_S3_DIVIDER		DT_QUICKLOGIC_EOS_S3_PWM_GEN_40020000_DIVIDER
#define DT_PWM_GEN_EOS_S3_NAME			DT_QUICKLOGIC_EOS_S3_PWM_GEN_40020000_LABEL

/* Set PWM0 to PAD18 */
#define PWM0_PAD18 (PAD_CTRL_SEL_FABRIC | PAD_OEN_NORMAL \
	| PAD_P_PULLDOWN | PAD_SR_SLOW | PAD_E_2MA \
	| PAD_REN_DISABLE | PAD_SMT_DISABLE)

/* Set PWM1 to PAD21 */
#define PWM1_PAD21 (PAD_CTRL_SEL_FABRIC | PAD_OEN_NORMAL \
	| PAD_P_PULLDOWN | PAD_SR_SLOW | PAD_E_2MA \
	| PAD_REN_DISABLE | PAD_SMT_DISABLE)

/* Set PWM2 to PAD22 */
#define PWM2_PAD22 (PAD_CTRL_SEL_FABRIC | PAD_OEN_NORMAL \
	| PAD_P_PULLDOWN | PAD_SR_SLOW | PAD_E_2MA \
	| PAD_REN_DISABLE | PAD_SMT_DISABLE)

#define PWM0_PAD		18
#define PWM0_PAD_CFG		PWM0_PAD18
#define PWM1_PAD		21
#define PWM1_PAD_CFG		PWM1_PAD21
#define PWM2_PAD		22
#define PWM2_PAD_CFG		PWM2_PAD22
#endif /* CONFIG_PWM_GEN_EOS_S3 */

#endif /* __INC_BOARD_H */
